// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVRqlJhhboxKs2paPc0D86NV4DdStgr1U',
    appId: '1:316719078092:web:7960338ba028af8d7dc069',
    messagingSenderId: '316719078092',
    projectId: 'melodyhub-4fad1',
    authDomain: 'melodyhub-4fad1.firebaseapp.com',
    storageBucket: 'melodyhub-4fad1.firebasestorage.app',
    measurementId: 'G-YTQVEE7622',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAxwlaraXaiFg6ikAq0sAn0IpSv5-h95g',
    appId: '1:316719078092:android:572426b49e09b2d77dc069',
    messagingSenderId: '316719078092',
    projectId: 'melodyhub-4fad1',
    storageBucket: 'melodyhub-4fad1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ4DOFyeubX0dJjReGztRjgluZLib6_Oc',
    appId: '1:316719078092:ios:4694bcef83674b527dc069',
    messagingSenderId: '316719078092',
    projectId: 'melodyhub-4fad1',
    storageBucket: 'melodyhub-4fad1.firebasestorage.app',
    iosBundleId: 'com.example.melodyhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ4DOFyeubX0dJjReGztRjgluZLib6_Oc',
    appId: '1:316719078092:ios:4694bcef83674b527dc069',
    messagingSenderId: '316719078092',
    projectId: 'melodyhub-4fad1',
    storageBucket: 'melodyhub-4fad1.firebasestorage.app',
    iosBundleId: 'com.example.melodyhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVRqlJhhboxKs2paPc0D86NV4DdStgr1U',
    appId: '1:316719078092:web:c091bce38d87a4c57dc069',
    messagingSenderId: '316719078092',
    projectId: 'melodyhub-4fad1',
    authDomain: 'melodyhub-4fad1.firebaseapp.com',
    storageBucket: 'melodyhub-4fad1.firebasestorage.app',
    measurementId: 'G-SQ2LHS6LTQ',
  );
}
